version: "2.0"
# Development Purposes only

networks:
  corp:
    driver: bridge

services:
  docdigital:
    image: docdigital-img
    container_name: docdigital
    networks:
      - corp
    build:
      context: .
    volumes:
      - ./dist:/app/dist
    ports:
      - "4000:80"
    env_file:
      - ./.env.production
